"""SAMPLEVERSION_AddedFixedEntityENUMTypeInBrandTable

Revision ID: 6a18cda21bb6
Revises: aaaf8bd71bd8
Create Date: 2024-12-02 12:43:07.611892

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6a18cda21bb6"
down_revision = "aaaf8bd71bd8"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
    CREATE TYPE fixedentitytypeenum AS ENUM ('person', 'company', 'event', 'government', 'educational', 'ngo', 'other');
    """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("brands", schema="my_schema") as batch_op:
        batch_op.alter_column(
            "fixed_entity_type",
            existing_type=sa.TEXT(),
            type_=postgresql.ENUM(
                "person",
                "company",
                "event",
                "government",
                "educational",
                "ngo",
                "other",
                name="fixedentitytypeenum",
            ),
            existing_nullable=True,
            postgresql_using="fixed_entity_type::fixedentitytypeenum",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("brands", schema="my_schema") as batch_op:
        batch_op.alter_column(
            "fixed_entity_type",
            existing_type=sa.Enum(
                "person",
                "company",
                "event",
                "government",
                "educational",
                "ngo",
                "other",
                name="fixedentitytypeenum",
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    # Drop the ENUM type 'licensabilityenum' in PostgreSQL
    op.execute("DROP TYPE fixedentitytypeenum;")

    # ### end Alembic commands ###
